### ISSUE TITLE
cancelling  of text annotation after publishing 

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/swtr#33] opened 2015-02-05 09:01 UTC
After publishing text annotation text in the publish box does not get cancelled and appears in the next annotation and gets published again.

**Comment by ecthiender** [comment] 2015-02-05 09:15
Can you explain in more details please? It is not clear from the above what you are trying to say.

**Comment by ecthiender** [comment] 2015-02-05 09:15
And also can you please change your username?

It is misleading!!

**Comment by Amrapalivishwa** [comment] 2015-02-10 11:19
After publishing text annotation sweet box should become empty instead it keeps text and next time i sweet other text from other html page, previously annotated text also reappears and gets published again with the new text annotation, if you visit sweet store you may understand. Only when i re-sign-in in restory.swtr.us previouse annotation does not reappear. Rightnow every time i am re-sign-in  to avoid suplication.

**Comment by ecthiender** [comment] 2015-02-11 19:19
Thanks. This issue is already reported before. See this issue: #19 

We are working on a fix for this soon.

For the meantime, you don't have to re-sign-in, you can just reload the page. It will clear out the older annotations.

**Comment by ecthiender** [comment] 2015-02-11 19:19
Duplicate of #19

**Closed as completed by ecthiender** 2015-02-11 19:19 UTC
Labels: bug, duplicate
