### ISSUE TITLE
Which are the various formats of images and webpages supported?

### ISSUE THREAD

**Issue by navyasn** [janastu/swtr#27] opened 2015-01-06 07:49 UTC
While trying with .jpg files and html pages, Annotation is working. However, some new formats like .gif are not working. Should this be supported?

**Comment by ecthiender** [comment] 2015-01-06 10:32
The following image works; which is a gif: http://servelots.com/images/logo_blue.gif

Which image did not work for you? Can you share the link?

Also, the following image formats _are_ supported: jpg, jpeg, png, gif, bmp, svg
(basically the formats natively supported by any standard browser)

If any image does not have an extension (.something), we try to fetch the image and see if it is among the supported images and then load it.

It'll be helpful if you can share the image link, and then we can all try to reproduce the error and see what is going wrong.

**Comment by ecthiender** [comment] 2015-01-29 14:26
Hi Navya,

Did you check this after that? Does it work with other gifs? Or does it fail?

Can you check with the same file again(on which it was failing)?

Let me know. We should follow up this issue.

**Comment by navyasn** [comment] 2015-01-30 04:55
Hi Anon,

I tried with the gif files today and they are working fine. I only had this
issue while using Windows OS.

Regards,
Navya

**Comment by ecthiender** [comment] 2015-01-30 05:38
Two questions:
1. Did you try with the same gif file, with which you faced the issue originally?
2. Can we test on a Windows machine again to be sure if this is an issue on Windows. (Technically, it should not be! All these are web apps!)

**Comment by navyasn** [comment] 2015-01-30 05:41
Yes, I tried with the same image again.
Let me check if I can get a windows machine to test again.

**Comment by ecthiender** [comment] 2015-01-30 05:51
Thanks! Hopefully we can close this issue after that! :)

**Comment by pradyumnat** [comment] 2015-01-30 09:27
Tried sweeting .gif images on windows8.1. works on mozilla, chrome and ie.

**Comment by ecthiender** [comment] 2015-02-03 14:17
So looks like we don't have this issue anymore. Closing this.

**Closed as completed by ecthiender** 2015-02-03 14:17 UTC
